version: '3'

services:
  frontend:
    image: node:14
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: npm install && npm start
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: python:3.8
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
